### ISSUE TITLE
Transfer Vercel integration

### ISSUE THREAD

**Issue by b-g** [alexabruck/reshape-website#1]
Hi @alexabruck, hope all is going well! Could you please transfer the Vercel integration back to us? (My Vercel account username is: b-g) Thanks! All the best, Benedikt cc @cpietsch @ron-mandic

**Comment by alexabruck** [comment]
Hi @b-g, Vercel lets me only transfer it to a team

**Comment by alexabruck** [comment]
Option 2 would be that I delete this project from my Vercel account, and you set it up new with your account

**Comment by b-g** [comment]
Thanks @alexabruck for the swift reply! We will check what the easiest way would be and get back to you.

**Comment by cpietsch** [comment]
Hey @alexabruck probably deleting it is the simplest way. Are there any env keys needed for the deployment? The domain is still pointing to it ?

**Comment by alexabruck** [comment]
@cpietsch Sure! I will delete it. No env variables needed.
Not sure if we should discuss deployment details in public Github comments tho :-D

Here is some  more information about the Domains:
- https://reshapeforum.hfg-gmuend.de is still pointing to the Vercel nameserver
- The domain reshapeforum.de has expired (you could reclaim it I guess)
- Originally reshapeforum.de redirected to hfg-gmuend.de

**Comment by cpietsch** [comment]
Thanks. This is valuable info.

**Comment by cpietsch** [comment]
@alexabruck have you cancel/deleted reshapeforum.de ? It is still online. Maybe somebody claimed it ?

**Comment by cpietsch** [comment]
We decided against reshapeforum.de domain - only using the subdomain-

**Comment by alexabruck** [comment]
The domain is offline
